berlin-hack-and-tell/bhnt.c-base.org

- README.md
> Add link to inboxSync

- README.md
> Add links for Brockman, Hackerfleet and SurvivalManual presentations

- README.md
@ligi I found "Ligi" and "ligi", and think that "ligi" is the correct spelling. Is it?
> Fix spelling of ligi

- README.md
> Fix formatting, author name and author link for kottpd

- README.md
> Remove order / numbers - use plain lists

- README.md
One BHNT issue a day keeps the meetup-data-silo away ;-)
I added all links from meetup and noflo from @bergie that I was aware of
> Add infos for bhnt 17 - closes #42

- README.md
As ligi said, one BHNT issue a day keeps the meetup-data-silo away.
> Add list of hacks for BHNT#16 (closes #41)

- README.md
Proposed by @bergie in https://github.com/berlin-hack-and-tell/berlin-hack-and-tell.github.io/pull/50#discussion_r100499282
> Improve link to NoFlo

- README.md
- the links from Keith 404ed so I left them out
- added the full names of the Claudio's to avoid collision
> Add BHNT 15 - closes #40

- README.md
This is based on the information given at https://github.com/berlin-hack-and-tell/berlin-hack-and-tell.github.io/pull/6#issuecomment-278802746
@Miserlou @MichaelKreil Can you confirm that I addressed this correctly to BHNT#41? Or, was it presented at another BHNT?
> Add Mate Light to BHNT#41

- README.md
Also, fix naming and link to Jose (prefering GitHub over Twitter) and remove some stray whitespaces.
> Add missing presenter (closes #49)

- README.md
Based on https://github.com/berlin-hack-and-tell/berlin-hack-and-tell.github.io/pull/69#discussion_r100788636
> Add missing links to BHNT#47

- README.md
Based on https://github.com/berlin-hack-and-tell/berlin-hack-and-tell.github.io/pull/72#discussion_r101646113
> Update author and project link of new BHNT timer

- README.md
evidence photo: https://www.meetup.com/Berlin-Hack-and-Tell/photos/26696876
> Add hack of the month info

- README.md
> Add mentioning in 33C3 talk

- README.md
Unfortunately, I was unable to reconstruct all presentations from Meetup.
> Add presentations of BHNT#25 (closes #17)

- README.md
Unfortunately not a lot of information to begin with and 2 of the urls that have been there 404ed - we need a permanent web.
> Add BHNT 12 - closes #16

- README.md
Replace pseudo by my real name and add a link to the WG Hunter gist.
Huge 👍 for this repo! Should be mentionned during the meetups as well.
> Update informations concerning myself

- README.md
Depends on  #101.
I'm unsure whether we should label it here as `#50` or `#0x0032`. I'm using `#0x0032` here because it is announced that way on Meetup.
> Add BHNT#50

- README.md
Trying to convert as much as possible until next BHNT meetup.
> Add presentations of BHNT#3 (closes #23)

- README.md
> Add presentations of BHNT#24 (closes #112)

- README.md
> Add presentations of BHNT#31 (closes #114)

- README.md
> Add presentations of BHNT#27 (closes #113)

- README.md
> Add presentations of BHNT#33 (closes #115)

- README.md
> Add presentations of BHNT#35 (closes #116)

- README.md
> Add presentations of BHNT#10 (closes #37)

- README.md
> Add presentations of BHNT#13 (closes #39)

- README.md
> Mark hack of the month for BHNT#16

- _config.yml
should give us a nicer title and help SEO ( #45 )
> Add configuration fields ( name / url / description )

- README.md
> Add all missing entries for BHNT#11 (closes #119)

- README.md
> Update link of "New BHNT website" project announced in BHNT#50

- README.md
> Fix project title, improve author information and mark Hack of the month of BHNT#17 (closes #60)

- README.md
See https://github.com/berlin-hack-and-tell/berlin.hackandtell.org/pull/128#pullrequestreview-24273622
> Fix naming and link to gobandroid

- README.md
> add link to Stadt, Land, Wikidata

- README.md
> Add all missing entries for BHNT#43, consistent link to ligi (closes #61)

- README.md
> Adjust date of BHNT#51

- README.md
Thanks for this great meetup and place!
> Add Visual TDD to Hack & Tell 51

- README.md
Thanks for this amazing experience!
> Adding mapscii

- README.md
> Add @cketti 's FamilyEmoji presentation at BHNT 51

- README.md
> Add missing presentation "xltrtr" (closes #169)

- index.md
> Additional information for BHNT#2 (#103)

- index.md
@blinry I was writing down david as a name for you - but github states a different one - can you please check if the name you want to use is used here?
cc @frehberg @dashersw
> Add BHNT 55 - "Post Eclipse Hacking"

- _posts/2018-01-30-no57-off-by-one.md
- a minute after the show ended
- untested ... works on my editor
> Add talks of BHNT #57.

- _posts/2018-02-27-no58-hacking-heavy.md
Add hacks for BHNT58 - cc @vog @stefanhoth @johnjohndoe
> Add hacks for BHNT#58

- _posts/2018-02-27-no58-hacking-heavy.md
Was pointing to some other repo
> Fix microflo-luftdaten link

- _posts/2018-02-27-no58-hacking-heavy.md
> Add talk by @KevinFrantz

- _posts/2018-03-27-no59-stephen-hacking.md
> Add link to Chris Chinchilla

- _posts/2018-03-27-no59-stephen-hacking.md
Added link to my very short code bit
> added link for illegal prime decoding

- _posts/2018-04-24-no60-hacker-hearing.md
> Add partitionhider by @nolash

- _posts/2018-05-29-no61-revolutionary-may-hacks.md
Happy when people can add more information - that's all I have for now - the whole projector situation was keeping me a bit occupied that show ^^
cc @lucasrangit @jpetazzo @wrl
> Add infos for BHNT61

- _posts/2018-05-29-no61-revolutionary-may-hacks.md
I'm sorry for delay, but usually it's better late than never 😄 Didn't know and didn't ask during BHNT#61 how to provide links.
I ❤️ BHNT! 😄
> Add links for LGTM Chrome extension

- _posts/2018-05-29-no61-revolutionary-may-hacks.md
Hey @ligi I moved my repo and fixed my name on the website. Please pull.
> Update BHNT61 link and name for NodeJS Vote by MAC

- _posts/2018-06-26-no62-summer-ish-hacks.md
@k-nut @stefanhoth did you get the project information for the Adventure game?
Signed-off-by: Lucas Magasweran <lucas.magasweran@ieee.org>
> BHNT62 add hacks (missing one)

- _posts/2018-06-26-no62-summer-ish-hacks.md
@ligi sorry about the broken links.
I didn't mean to leave them there. I thought it would be filled in before merging.
> BHNT62: remove incomplete markup to not have broken links

- _posts/2018-07-31-no63-meltdown.md
@k-nut I'm only missing the code for the cow jokes. Do you have a gist for that?
> BHNT63: add

- _posts/2018-07-31-no63-meltdown.md
> Fixed typo

- _config.yml
- _layouts/default.html
This is the first draft for #220. 
Feel free to change the wording or add your input if this should be positioned somewhere else on the page 🙂
> describe the format of bhnt on the landing page

- _posts/2018-08-28-hackable.md
I think we should always kick of a new BHNT edition via PR from this anniversary on ;-)
> Adding BHNT 64 - Hackable

- _posts/2018-08-28-no64-hackable.md
Tested the links and found two bad ones.
> BHNT 64 fix some links

- _posts/2018-09-25-no65-dear-moon-hacks.md
I only have limited info as I was not in Berlin unfortunately - but it is at least start ..-)
perhaps @lucasrangit @vog @rtens @johnjohndoe @SP4CEberlin @ihucos @chr5tphr can add some more info later on
> Add BHNT 65 info

- _posts/2018-09-25-no65-dear-moon-hacks.md
Based on @ligi 's PR #232 (with commits). Don't think I can push to that branch since it's in a fork.
Only missing the Qdolphin browser project link.
> v2 Add BHNT 65

- _posts/2018-11-27-no66-every-hack-is-a-target.md
here are the hacks. missing only the overflow hack.
> bhnt 66: add hacks

- _posts/2017-04-25-no51-twice-as-good.md
Added the information from the ticket #164 to the best of my abilities.
For @tasomaniac's demo of ImmoSnake I'm pretty sure they couldn't provide the source code.
And I might remember wrongly but Adam probably also said that he couldn't upload this without risking trouble with them. 😈
> Add more info to no51, fixes #164

- _posts/2019-01-29-no67-hacking-memories.md
I think I have most presentations - still missing the Hack of the Month - anyone has infos about this one?
cc @k-nut @chriseth @MichaelKreil @jpeinelt @sebastian-guent\
her @stefanhoth @benjaminwand @Wikinaut @lucasrangit
> Add BHNT 67 - Hacking Memories

- _posts/2019-02-26-no68-de-obfuscate-your-hacks.md
still missing some links - but better than nothing - perhaps @lucasrangit @nolash @ChrisChinchilla @ciex @vog @fuzxxl can fill in some blanks
> Add BHNT 68

- _slides/2019-03-26-no69-upload-your-hacks.md
I could rebase this to have one nice or we could squash it with the Github feature into one commit. Whatever you all prefer 🙏
> Add slide for #69

- _posts/2019-05-28-no71-electing-hacks.md
https... one day i will get there
> Fix blog link for Qaiser's blog entry

- _posts/2019-06-25-no72-off-by-one.md
Context: https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/issues/254#issuecomment-516020134
> Reflect teg movement

- _slides/2019-09-24-no74-post-cccamp19-hacks.md
> bhnt-74: initial slides

- _posts/2019-10-29-no75-open-hardware-hacks.md
- _slides/2019-10-29-no75-open-hardware-hacks.md
I'm missing details for the winner.
> bhnt 75 add hacks and update title

- _posts/2019-10-29-no75-open-hardware-hacks.md
- _posts/2019-11-26-no76-cyber-hacks.md
- Removed links from .md files that weren't linking anything.
- Changed name from sva in #76 to lowercase (she insisted)
----
I don't know the name of the winner from #75
> removed dead links from posts

- _posts/2019-11-26-no76-cyber-hacks.md
Improve Surrogates entry for BHNT#76, according to Sebastian's email.
> Improve Surrogates entry for BHNT#76

- _posts/2020-02-25-no78-flash-your-hacks.md
- _slides/2020-02-25-no78-flash-your-hacks.md
I'm updating the missing hacks and also testing the github workflow action to validate the URLs.
> bhnt-78: add missing hacks

- _posts/2019-05-28-no71-electing-hacks.md
This entry received a sequel today.
> Fix entry of BHNT#71

- _posts/2021-10-26-no80-0b10G.md
Still some info missing - but at least a start - maybe  @TimDaub @jzilg @lavielle @qaismyname @herrmuellerluedenscheid @johnjohndoe can add more details?
> Add BHNT80 hacks

- LICENSE.txt
- Reference: https://github.com/berlin-hack-and-tell/berlinhackandtell.rocks/issues/304#issuecomment-966235557
> Add license (CC0).

- .github/workflows/urlchecker-pr-label.yml
- _posts/2022-05-31-no81-rebooting-bhnt.md
BHNT82 Notes:
Slot0: Alex - Lightbox for toddler [https://www.reddit.com/r/DIY/comments/sar7t1/our_two_year_old_loves_to_flick_the_lights_so_i/]
Slot1: Kevin - docker volume backup [https://github.com/kevinveenbirkenbach/docker-volume-backup]
Slot2: Chazza - At Home With The GitOps [https://github.com/whalecoiner/home]
Slot3: Christoph - Nut Job (Treefinder for squirrels) [https://github.com/cfretter/eichhoernchen-shdb2019]
Slot4: Ramzi - MarioDemo [https://github.com/RamziKhahil/MarioDemo]
Slot5: dukpt - CVE-2020-9273 ProFTPd exploitation of a use-after-free [https://github.com/ptef/CVE-2020-9273]
Slot6: buoyantair - yt2pt (Youtube to Peertube Channel transfer) [https://github.com/buoyantair/yt2pt]
Slot7: quitty - Goth jwt [http://github.com/quittymr/goth]
> Add BHNT 81 hacks from https://pad.systemli.org/p/bhnt082

- _slides/2022-05-31-no81-rebooting-bhnt.md
> Improve slides (#312)

- _posts/2022-11-29-no83-hacks-sink-in.md
cc @timdaub @vog @langa-me @echtzeit-dev
> Add BHNT 83 hacks/post

- _posts/2022-12-27-no84-hacks-in-parallel.md
cc @soulim @michaelkreil @cfcs @frehberg @neopostmodern @crest
> Add BHNT84 hacks

- _posts/2023-01-31-no85-illuminati-hacks.md
I just created a repo for my hack and I wanted to add it to the list :)
> Add link to mpv-midi-controller hack

- _posts/2023-03-28-no87-h4k.md
Thanks @vog - used your script the first time - worked nice!
> Add BHNT87

- _posts/2023-03-28-no87-moore-hacks.md
In honor to Gordon Moore who passed last week
> Rename to Moore Hacks

- _posts/2023-03-28-no87-moore-hacks.md
cc @andrewtavis , @steely-glint , @danielpaulus , @kevinveenbirkenbach , @chemaclass , @davedarko , @herrmuellerluedenscheid , @k-nut
> Add hacks for BHNT 87

- _posts/2023-04-25-no88-shacka.md
unfortunately pad did get deleted as the expiry was before this PR - so some info missing - if anyone has info about missing projects - LMK
cc @ianklatzco @lordofthelake @cesena @leopic @algroznykh
> Add hacks for BHNT88

- _posts/2023-07-25-no89-camping-hacks.md
hacks for BHNT89
@arrybn @uwekamper @Wikinaut @vog @030jmk @lgrammel @0xAverageUser : Thanks everyone for presenting - please check if your entries are OK
> Add hacks for BHNT89

- _posts/2023-07-25-no89-camping-hacks.md
> Switch GitHub link with website link of vog

- Gemfile
- Gemfile.lock
without this I had problems running on a clean install
> Add webrick

- _posts/2023-04-25-no88-shacka.md
I changed the project name to Commitspark since my presentation. Feel free to change it here as well.
(This PR also needs the `needs-url-checks` label but I don't appear to have label assignment rights.)
> Add link to project

- _posts/2023-09-26-no90-post-utopia-hacks.md
Hey @ligi thanks for pushing the latest post. I just fixed the ichbinkeinvirus link and also provided the link to the source code of the moderation tool.
> change links for ichbinkeinvirus

- _posts/2023-09-26-no90-post-utopia-hacks.md
linking my hack :) sorry seems like I wrote in the wrong pad or maybe the changes didn't sync, either way, fixing the link!
> update link to music visualizer

- _posts/2022-11-29-no83-hacks-sink-in.md
- _slides/2022-11-29-no83-hacks-sink-in.md
> Fix date for BHNT83

- _posts/2023-10-31-no91-hacks-of-spooky-times.md
cc @artfwo @vrde @vog @wleuschner @ugogon @ArchGPT
> Add hacks for BHNT 91

- copy-announcement.sh
so it now includes creating the slide scaffold
> Improve copy announcement

- _posts/2023-11-28-no92-closedai-hacks.md
otherwise jekyll does not seem to like it
> Repace tab with 4 spaces

- _posts/2023-11-28-no92-closedai-hacks.md
https://stackoverflow.com/questions/56970589/how-to-add-an-image-for-twitter-cards-on-with-posts-with-jekyll-seo-tag
> Try fix the X card

- _posts/2023-11-28-no92-closedai-hacks.md
cc @KaeruCT @wleuschner @weliveindetail @isaksolheim @PiXeL16
> Add BHNT 92 hacks

- README.md
> Improve README to document an alternative setup without Docker

- _config.yml
- _layouts/default.html
> Improve social links

- _posts/2024-01-30-no93-unlocked-hacks.md
cc @ricott1 @kevinveenbirkenbach @davidspeith @janek @0xRamsi @karlb @hartwork
> Add hacks for BHNT93

- _posts/2024-02-27-no94-reality-hacks.md
cc @hartwork @vrde @herrherrmann @leopic @strathausen @ricott1
> Add hacks for BHNT 94

- _posts/2024-03-26-no95-devin-s-hacks.md
cc @pan-maruda @WolframHempel @kevinveenbirkenbach @excds @ArthurTent @leif @wleuschner
> Add hacks for BHNT 95

- _posts/2024-05-28-no96-portal-hacks.md
> Add trovu.net.

- _posts/2024-05-28-no96-portal-hacks.md
ready for public consumption now 🤣
> add eInk BVG display repo link to BHNT96

- _posts/2023-11-28-no92-closedai-hacks.md
> add a link to project

- _posts/2024-07-30-no97-crowdstruck.md
PTAL: @MichaelKreil @hannob @ctrlw @strathausen @soulim
> Add hacks for BHNT97

- _posts/2024-08-27-no98-groky-hacks.md
cc @RuggedOdyssey @Wikinaut @paulengstler @HasanShaukat @bplevin36 @deeecent
> Add hacks for BHNT98

- _slides/2024-08-27-no98-groky-hacks.md
- copy-announcement.sh
already used a lot of these changes last months, but did not reflect here yet
> Change copy

- _posts/2024-09-24-no99-reasoning-hacks.md
cc @Sir-Jude @ricott1 @HasanShaukat @lowlorenz  @karlb @Freika @JonasLoos
> Add hacks for BHNT99

- _posts/2024-09-24-no99-reasoning-hacks.md
> fixed wrong github link in 2024-09-24-no99-reasoning-hacks.md

- _posts/2024-10-29-no100-annivercary.md
cc @uwekamper @Make-Europe @hartwork @altsoph @artfwo @Chemaclass
will merge directly to not have this now wrong "Upcoming" for too long - but please have a look and fix things if we got something wrong!
> Add Hacks for BHNT100

- _posts/2025-01-28-no101-singularity-inauguration-hacks.md
cc @nerdmaennchen @altsoph @kevinveenbirkenbach @penyaev @Tienisto  @vog
> Add hacks for BHNT101

- README.md
> Improve docker build instructions to be on par with the local build

- copy-announcement.sh
Add final slide as background for winner photo
> Add final slide as background for winner photo

- _posts/2025-02-25-no102-gulf-of-hacks.md
cc @MarlonSchultz @MichaelKreil @KaeruCT @soulim @bashtian  @HasanShaukat @mariannespijkstra
> Add hacks for 102

- _posts/2025-04-29-no103-plutocracy-on-signal.md
@MichaelKreil @steely-glint @johan-t @kevinveenbirkenbach @udinanon @vog @mknz @victordiaz
> Add hacks for BHNT 103

- _posts/2025-05-27-no104-habemus-hacker.md
@pkoryzna @ziina @ctrlw @excds @vog @cfretter
> Add hacks for 104

- _posts/2025-07-29-no105-mechahacker.md
cc @ihucos @strathausen @victordiaz
> Add hacks for BHNT 105

- _posts/2025-09-30-no106-hacks-of-30years-cbase.md
@michaelkreil @uwekamper @vog @shift @ri0t @l5yth @riskieee
> Add hacks for BHNT 106
